// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace SmartWarehouse
{
    public partial class SatisTahminModeli
    {
        /// <summary>
        /// model input class for SatisTahminModeli.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"SatisId")]
            public float SatisId { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"Adet")]
            public float Adet { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"Tutar")]
            public float Tutar { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"Tarih")]
            public DateTime Tarih { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"UrunId")]
            public float UrunId { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"MusteriId")]
            public float MusteriId { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for SatisTahminModeli.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"SatisId")]
            public float SatisId { get; set; }

            [ColumnName(@"Adet")]
            public float Adet { get; set; }

            [ColumnName(@"Tutar")]
            public float Tutar { get; set; }

            [ColumnName(@"Tarih")]
            public DateTime Tarih { get; set; }

            [ColumnName(@"UrunId")]
            public float UrunId { get; set; }

            [ColumnName(@"MusteriId")]
            public float MusteriId { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

       
        private static string MLNetModelPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "bin", "SatisTahminModeli.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
